# AUTOGENERATED! DO NOT EDIT! File to edit: 02_pipeline.ipynb (unless otherwise specified).

__all__ = ['logger']

# Cell
import logging
import os
from pathlib import Path

from pyciss import io
import subprocess

try:
    from kalasiris import (
        ciss2isis,
        cisscal,
        dstripe,
        editlab,
        getkey,
        isis2std,
        ringscam2map,
        spiceinit,
        fillgap,
    )
except ImportError:
    print("Cannot load the ISIS system. pipeline module not functional.")
else:
    ISISDATA = Path(os.environ["ISISDATA"])
    ISISROOT = Path(os.environ["ISISROOT"])
# from kalasiris.pysis import ProcessError

logger = logging.getLogger("pyciss.pipeline")