# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "02_pipeline.ipynb",
         "configpath": "00_io.ipynb",
         "get_config": "00_io.ipynb",
         "set_database_path": "00_io.ipynb",
         "get_db_root": "00_io.ipynb",
         "db_mapped_cubes": "00_io.ipynb",
         "db_label_paths": "00_io.ipynb",
         "PathManager": "00_io.ipynb",
         "DBManager": "00_io.ipynb",
         "base_url": "01_opusapi.ipynb",
         "metadata_url": "01_opusapi.ipynb",
         "image_url": "01_opusapi.ipynb",
         "dic": "01_opusapi.ipynb",
         "MetaData": "01_opusapi.ipynb",
         "OPUSImageURL": "01_opusapi.ipynb",
         "OPUSObsID": "01_opusapi.ipynb",
         "OPUS": "01_opusapi.ipynb"}

modules = ["io.py",
           "opusapi.py",
           "pipeline.py"]

doc_url = "https://michaelaye.github.io/pyciss2/"

git_url = "https://github.com/michaelaye/pyciss2/tree/master/"

def custom_doc_links(name): return None
