# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "04_plotting.ipynb",
         "Config": "00_io.ipynb",
         "config": "00_io.ipynb",
         "get_db_root": "00_io.ipynb",
         "PathManager": "00_io.ipynb",
         "db_mapped_cubes": "00_io.ipynb",
         "db_label_paths": "00_io.ipynb",
         "DBManager": "00_io.ipynb",
         "filename_from_obsid": "00_io.ipynb",
         "base_url": "01_opusapi.ipynb",
         "metadata_url": "01_opusapi.ipynb",
         "image_url": "01_opusapi.ipynb",
         "dic": "01_opusapi.ipynb",
         "MetaData": "01_opusapi.ipynb",
         "OPUSImageURL": "01_opusapi.ipynb",
         "OPUSObsID": "01_opusapi.ipynb",
         "OPUS": "01_opusapi.ipynb",
         "get_order": "03_ringutils.ipynb",
         "get_resonances": "03_ringutils.ipynb",
         "get_prime_resonances": "03_ringutils.ipynb",
         "get_janus_epimetheus_resonances": "03_ringutils.ipynb",
         "get_prime_jan_epi": "03_ringutils.ipynb",
         "get_all_prime_resonances": "03_ringutils.ipynb",
         "which_epi_janus_resonance": "03_ringutils.ipynb",
         "lookup_rcparam": "04_plotting.ipynb",
         "myimshow": "04_plotting.ipynb",
         "myinteract": "04_plotting.ipynb",
         "imshowlowhigh": "04_plotting.ipynb",
         "add_ticks_to_x": "04_plotting.ipynb",
         "get_res_radius_from_res_name": "04_plotting.ipynb",
         "resonance_table": "04_plotting.ipynb",
         "interpolators": "04_plotting.ipynb"}

modules = ["io.py",
           "opusapi.py",
           "pipeline.py",
           "ringutils.py",
           "plotting.py"]

doc_url = "https://michaelaye.github.io/pyciss2/"

git_url = "https://github.com/michaelaye/pyciss2/tree/master/"

def custom_doc_links(name): return None
